[project]
name = "fastapi-code-platform"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
  "fastapi",
  "uvicorn",
  "sqlalchemy>=2.0",
  "aiomysql",
  "pydantic",
  "redis>=5",
  "python-jose",
  "passlib[bcrypt]",
  "docker",
  "orjson"
]
